# Generated by Django 2.1.3 on 2018-12-02 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_product_usercart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='userCart',
        ),
        migrations.AddField(
            model_name='product',
            name='userCart',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
