# Generated by Django 2.1.3 on 2018-12-04 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20181202_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='userCart',
        ),
    ]
