# Generated by Django 2.1.3 on 2018-12-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181207_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(default='No Description'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='quote',
            field=models.TextField(default='No Quote'),
        ),
    ]
